[tools]
scala = "3.6.3"
java = "temurin-21.0.6+7.0.LTS"

[tasks.download-javaagent]
run = """
if [ ! -f "opentelemetry-javaagent.jar" ]; then
    wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.12.0/opentelemetry-javaagent.jar
else
    echo "javaagent already downloaded"
fi
"""

[tasks.package]
sources = ["CameloServer.scala"]
outputs = ["camelo.jar"]
run = """
scala \
    --power \
    package . \
    -o camelo.jar \
    --assembly \
    --preamble=false \
    --force
"""

[tasks.server-start-with-otel]
depends = ["package", "download-javaagent"]
run = """
java \
    -javaagent:opentelemetry-javaagent.jar \
    -Dotel.metric.export.interval=2000 \
    -jar camelo.jar
"""

[tasks.server-log-otel-startup]
depends = ["package", "download-javaagent"]
run = """
java \
    -Dotel.javaagent.debug=true \
    -javaagent:opentelemetry-javaagent.jar \
    -jar camelo.jar &> server-otel-startup.log
"""

[tasks.server-start]
run = "scala run CameloServer.scala"